### ISSUE TITLE
Paper - Possible (minor) error

### ISSUE THREAD

**Issue by afiaka87** [microsoft/NUWA#3]
> In this paper, we show that simply using 2D VQ-GAN to encode each frame of a video can also generate **temporal consistency** videos and at the same time benefit from both image and video data.

In the paper, I believe you mean "temporally consistent" here. Subtle change in wording.

**Comment by chenfei-wu** [comment]
Thank you for your suggestion!

**Comment by afiaka87** [comment]
No problem - excited to see the results!
